### PR TITLE
update project and tag new version

### PR DESCRIPTION
**Pull request by CarloLucibello**

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Why are we removing the docs manifest?

**Comment by CarloLucibello** [comment]
> Why are we removing the docs manifest?

Documenter's docs just suggest to have Project.toml with a compact entry. Why do we have a manifest?

**Comment by dhairyagandhi96** [comment]
So we can push out docs updates with a reproducible environment and so we can push doc updates without a new release everytime

**Pull request merged**
