### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by willtebbutt**
The current README is a bit misleading in terms of performance, because Zygote really doesn't have good performance when control flow is involved. I'm open to other suggestions for re-wording, but it seems reasonable to me that we temper what is currently there a bit.

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Zygote uses the IR Julia produces, and the compiler can strip off the branching when it's not needed, so it doesn't need to carry it around unnecessarily. We need a compiler pass post optimisation too, I think that would massively change what all we can do it terms of handling code.

**Comment by willtebbutt** [comment]
> Zygote uses the IR Julia produces, and the compiler can strip off the branching when it's not needed, so it doesn't need to carry it around unnecessarily. We need a compiler pass post optimisation too, I think that would massively change what all we can do it terms of handling code.

Certainly, you'll find no disagreement from me there, but that's future work, and doesn't reflect the current state of the package. Are you happy to update the readme as I propose, or is there something else that you would prefer?

**Comment by DhairyaLGandhi** [comment]
I feel like we can add it. Zygote is pretty close to optimal on enough of Julia that I wouldn't call it slow, by any means. I think that message should get spoken about too.

**Comment by willtebbutt** [comment]
> I feel like we can add it.

Sorry, add which bit? Please feel free to provide a suggestion :)

**Comment by DhairyaLGandhi** [comment]
Add (or rather remove the statement) the suggestion in the PR.

**Comment by willtebbutt** [comment]
Cool. If you approve, I'll merge :)

**Review by DhairyaLGandhi — APPROVED** [review]

**Pull request merged**
