### PR TITLE
Dispatch on AContext

### PR DESCRIPTION
**Pull request by willtebbutt**
Some of the rules in lib/lib have concrete type constraints to `Context`, rather than the (abstract) `AContext`. This has caused me some problems while playing around with my own subtype of `AContext`.

@DhairyaLGandhi  do you reckon this is going to be okay? I can't forsee it causing problems, but I'm not sure if I'm missing something important.

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Should be fine.

**Review by DhairyaLGandhi — APPROVED** [review]

**Comment by willtebbutt** [comment]
@DhairyaLGandhi any idea what's going on with the gitlab builds? Doesn't appear to be something I've changed I don't think...

**Comment by DhairyaLGandhi** [comment]
I'm not certain, maybe out of sync pkg servers?

**Comment by willtebbutt** [comment]
Interesting. I noticed a thing recently where my docs CI couldn't find a new version of a package that was definitely merged into the general registry -- could be the same thing?

**Comment by DhairyaLGandhi** [comment]
Possibly. Hard to say for sure, but we are running identical test suites on both. I might check the versions for loop vectorisation related packages.

**Comment by CarloLucibello** [comment]
tests here are passing on my gpu machine, we could manually merge this

**Comment by willtebbutt** [comment]
> tests here are passing on my gpu machine, we could manually merge this

I'm fine with this if @DhairyaLGandhi is

**Comment by DhairyaLGandhi** [comment]
Could we do a run with `JULIA_PKG_SERVER=""` to test the theory?

Other than that, I think we should be fine to merge this once.

**Comment by willtebbutt** [comment]
> Could we do a run with JULIA_PKG_SERVER="" to test the theory?

What would this involve? Is this a command line argument when you start up Julia, or something relating to CI?

**Comment by willtebbutt** [comment]
Bump @DhairyaLGandhi

**Comment by DhairyaLGandhi** [comment]
Oh, yeah, it's a env var you would set while starting Julia. But I think there were other ci runs that passed, so im going to try calling bors to hopefully it gets it in, else we can do it manually for now.

bors r+

**Pull request merged**
