### PR TITLE
Add dims kwargs and improve gradient computation for logsumexp

### PR DESCRIPTION
**Pull request by xukai92**

### CODE REVIEW

**Comment by MikeInnes** [comment]
Could use tests but otherwise looks good to me.

**Comment by xukai92** [comment]
Sorry I might miss something. What do you mean by "use tests"?

**Comment by MikeInnes** [comment]
Just mean it would benefit from a test or two to demonstrate the improvements you've made.

**Comment by xukai92** [comment]
I added a test and it passes.

**Comment by MikeInnes** [comment]
Thanks!

bors r+

**Pull request merged**
