### PR TITLE
Add a few methods to `Buffer` to make it behave like an `Array`

### PR DESCRIPTION
**Pull request by YingboMa**
This PR will fix the test failures in https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/pull/71

### CODE REVIEW

**Comment by MikeInnes** [comment]
Thanks – we could probably use `@forward` from MacroTools to make this a bit neater.

**Comment by YingboMa** [comment]
Thanks for the suggestion. I have updated the code.

**Comment by ChrisRackauckas** [comment]
Fixes https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/pull/71

**Comment by MikeInnes** [comment]
:+1: Thanks!

**Pull request merged**
