### PR TITLE
Add adjoints for optimized implementations of reduce([hv]cat, A)

### PR DESCRIPTION
**Pull request by AzamatB**
Adjoints for [#27188](https://github.com/JuliaLang/julia/pull/27188).

### CODE REVIEW

**Comment by AzamatB** [comment]
Bump

**Comment by CarloLucibello** [comment]
looks good! do we have tests for `reduce(vcat, xs...)` already? If not, could you add them?

**Comment by dhairyagandhi96** [comment]
Adding tests would be awesome, if we don't have them already.

Love to see this in

**Comment by dhairyagandhi96** [comment]
Bump

**Comment by piever** [comment]
Can probably be closed now that ChainRules implements those: https://github.com/JuliaDiff/ChainRules.jl/pull/236

**Comment by DhairyaLGandhi** [comment]
Oop, thanks all!

**Pull request closed without merging**
