### PR TITLE
Patch map bug

### PR DESCRIPTION
**Pull request by willtebbutt**
Fixes a bug in which when the input to map is a vector, but the adjoint is a `Tuple` the reversal doesn't happen.

This is a patch rather than a proper fix -- really this situation shouldn't ever occur.

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
We prolly need to keep the tests around.

**Comment by DhairyaLGandhi** [comment]
Note, #777 reverses some of the `reverse` work here.

**Comment by willtebbutt** [comment]
> We prolly need to keep the tests around.

😂 

> Note, dg/stateful_bcast reverses some of the reverse work here.this is needed for the lstm issue in Flux.

Could you point me towards that?

**Comment by DhairyaLGandhi** [comment]
https://github.com/FluxML/Zygote.jl/blob/21f07b450ddfe2e4ba6196b3edd8ed08f656e5e3/src/lib/array.jl#L191

**Comment by willtebbutt** [comment]
Okay, that looks like a nice change. The tests I've added here would be handy in that though, so it might make sense to go ahead and merge this.

This appears to be passing on 1.3. How are we going about merging stuff at the minute with master broken on 1.5?

**Comment by DhairyaLGandhi** [comment]
Currently I have not updated bors to Julia 1.5, although you might want to check against https://github.com/FluxML/Zygote.jl/pull/772. I want to make this backwards compatible and fix the incorrect gradient.

**Review by DhairyaLGandhi — APPROVED** [review]
bors r+

**Pull request merged**
