### PR TITLE
Handle nothing in map

### LINKED ISSUE #804: Unused comprehension throws "iterate(nothing)" method error
MWE:

```julia
using Zygote

function h(x)
    [2 for i in 1:2]
    sum(x)
end

gradient(h, zeros(2)) # ERROR: MethodError: no method matching iterate(::Nothing)
```

### PR DESCRIPTION
**Pull request by 0**
I ran into #804, and made an attempt to fix it before I noticed #846.

Unlike #846, which still runs `map`, this patch fixes #804 by propagating `Δ === nothing` through the `∇map` pullback more directly.

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Cc @oxinabox

**Comment by oxinabox** [comment]
This is much less weird to me.
Let's do this

**Review by oxinabox — APPROVED** [review]

**Comment by DhairyaLGandhi** [comment]
We'd return that tuple generically, so there might be some unforeseen consequences to consider.

**Comment by 0** [comment]
That's a good point. I was focused on the [`_pullback` for `collect`](https://github.com/FluxML/Zygote.jl/blob/2d5edf44ad7191fcd5d5816d8ab161dff8e14765/src/lib/array.jl#L236-L242) and neglected the general case. For example, the patch currently results in the following:
```julia
julia> Zygote.∇map(Zygote.Context(), +, [1.0], [1.0])[2](1.0)
(nothing, [1.0], [1.0])

julia> Zygote.∇map(Zygote.Context(), +, [1.0], [1.0])[2](nothing)
(nothing, nothing)
```

It also doesn't work for the empty array case, because that's handled in the other branch:
```julia
julia> gradient([]) do xs; [x for x in xs]; 0.0; end
ERROR: MethodError: no method matching iterate(::Nothing)
```

---

Since `∇map` [already returns](https://github.com/FluxML/Zygote.jl/blob/2d5edf44ad7191fcd5d5816d8ab161dff8e14765/src/lib/array.jl#L202) `_ -> nothing` when `args` are empty, callers should presumably be ready for this. Would it therefore be better to have
```julia
isnothing(Δ) && return nothing
```
instead of returning a tuple, and simply make sure that it's handled correctly at [line 239](https://github.com/FluxML/Zygote.jl/blob/2d5edf44ad7191fcd5d5816d8ab161dff8e14765/src/lib/array.jl#L239)? That might be the least weird option.

**Comment by CarloLucibello** [comment]
> Would it therefore be better to have

that seems a good solution, also what was discussed [here](https://github.com/FluxML/Zygote.jl/pull/846#issuecomment-739435872)

**Review by oxinabox — APPROVED** [review]

**Comment by DhairyaLGandhi** [comment]
Were the failing cases tested for @0 ?

**Pull request merged**
