### PR TITLE
1.4 updates

### LINKED ISSUE #393: ERROR: InitError: LoadError: Can't differentiate loopinfo expression
This is on a 3 day old master branch of Julia:
```
Julia Version 1.4.0-DEV.427
Commit c7e4b9929b* (2019-11-02 09:58 UTC)
```
And occurs when `using Zygote`:
```julia
julia> using Zygote
[ Info: Precompiling Zygote [e88e6eb3-aa80-5325-afca-941959d7151f]
ERROR: InitError: LoadError: Can't differentiate loopinfo expression
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion [inlined]
 [3] copyto! at ./broadcast.jl:908 [inlined]
 [4] copyto! at ./broadcast.jl:863 [inlined]
 [5] (::typeof(∂(copyto!)))(::FillArrays.Fill{Float32,1,Tuple{Base.OneTo{Int64}}}) at /home/chriselrod/.julia/packages/Zygote/mMAdj/src/compiler/interface2.jl:0
 [6] copy [inlined]
 [7] materialize at ./broadcast.jl:819 [inlined]
 [8] #1487 at /home/chriselrod/.julia/packages/Zygote/mMAdj/src/precompile.jl:22 [inlined]
 [9] (::typeof(∂(#1487)))(::Float32) at /home/chriselrod/.julia/packages/Zygote/mMAdj/src/compiler/interface2.jl:0
 [10] (::Zygote.var"#28#29"{typeof(∂(#1487))})(::Float32)
 [11] gradient(::Function, ::Array{Float64,1})
 [12] top-level scope at /home/chriselrod/.julia/packages/Zygote/mMAdj/src/precompile.jl:22
 [13] include(::Module, ::String) at ./Base.jl:377
 [14] include [inlined]
 [15] precompile at /home/chriselrod/.julia/packages/Zygote/mMAdj/src/Zygote.jl:43 [inlined]
 [16] (::Zygote.var"#1477#1478")() at /home/chriselrod/.julia/packages/Requires/9Jse8/src/init.jl:11
 [17] __init__()
 [18] _include_from_serialized(::String, ::Array{Any,1})
 [19] _require_from_serialized(::String)
 [20] _require(::Base.PkgId)
 [21] require(::Base.PkgId) (repeats 2 times)
in expression starting at /home/chriselrod/.julia/packages/Zygote/mMAdj/src/precompile.jl:22
during initialization of module Zygote
```
The error message from https://github.com/FluxML/Zygote.jl/issues/229 sounds similar, but am guessing they're different problems. Feel free to close if this is a duplicate.

EDIT:
The error also shows up here: https://travis-ci.org/FluxML/Zygote.jl/jobs/608155890

### PR DESCRIPTION
**Pull request by MikeInnes**
fixes #393, partially addresses #449 (this doesn't fully support apply_iterate but should address the most common cases).

bors r+

### CODE REVIEW

**Comment by MikeInnes** [comment]
This passed locally. Merging so we can fix PkgEval.

**Comment by dhairyagandhi96** [comment]
Worth noting that the manifest shows jll files which means that development will have to shift to Julia 1.3+ and bors works on 1.0

**Comment by MikeInnes** [comment]
Yup, we better fix bors and travis to use 1.3.

**Pull request merged**
