### PR TITLE
fix adjoint for sum

### PR DESCRIPTION
**Pull request by simeonschaub**
addresses the second part of #897

### CODE REVIEW

**Review by CarloLucibello — APPROVED** [review]

**Review by DhairyaLGandhi — COMMENTED** [review]
bors r+

**Comment by CarloLucibello** [comment]
I don't think bors failure is related https://buildkite.com/julialang/zygote-dot-jl/builds/214#78e9850d-b908-44e5-badb-1004d9e21153

In the failing cholesky test we should probably have `≈`  instead of `==`

**Comment by cpfiffer** [comment]
Could we bump this one? It'd be helpful for a project I'm on.

**Pull request merged**
