### PR TITLE
nograd typejoin

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
Should fix the issue @jonathan-laurent

### CODE REVIEW

**Comment by willtebbutt** [comment]
@DhairyaLGandhi would you consider doing this using `@non_differentiable` inside `ChainRules` instead of adding it here?

**Comment by DhairyaLGandhi** [comment]
I guess that's fine, but I was hoping to make a release with this to unblock AlphaZero

**Comment by willtebbutt** [comment]
> I guess that's fine, but I was hoping to make a release with this to unblock AlphaZero

We make a patch release with every non-breaking change in ChainRules, so you'll have a release to bind to :)

**Comment by DhairyaLGandhi** [comment]
Fixed in https://github.com/JuliaDiff/ChainRules.jl/pull/398

**Pull request closed without merging**
