### PR TITLE
adjoints for cumsum and cumprod

### PR DESCRIPTION
**Pull request by kraftpunk97-zz**
Another attempt at #282 . 

`cumsum` is just `reverse(cumsum(reverse(∆, dims=dims), dims=dims), dims=dims)`, as suggested by @mcabbott .

With `cumprod`, I had help from @dhairyagandhi96 who asked me to refer to [PyTorch's implementation](https://github.com/pytorch/pytorch/blob/0764d73d6b2a2acf4e02984859a3f329fb908653/torch/autograd/_functions/tensor.py#L589)

I've had no way to test my gradients except for comparing my results with that of `torch.cumprod` for same inputs, so I haven't added any tests yet

### CODE REVIEW

**Comment by kraftpunk97** [comment]
Another thing that comes to mind... I've had trouble getting the adjoints to work if I define them directly for the functions. However, if I wrap them around another function (like `my_cumprod` or `my_cumsum`) and then call the `gradient` on these wrapper functions, they work.

The error I get in the first case is a `DimensionMismatchError`. I have copied the [stack trace](https://gist.github.com/kraftpunk97/ef57003649f6f9608082695adf3cdfa3) I get for `cumprod`.

**Comment by dhairyagandhi96** [comment]
Something seems to have messed up in this commit?

**Comment by kraftpunk97** [comment]
It's probably nothing. When I open the file in Github's editor, the formatting seems fine.

**Comment by dhairyagandhi96** [comment]
Good to look into why, probably just editor settings.

**Comment by kraftpunk97** [comment]
Unable to identify issue. Although I did find the same behaviour on [here](https://github.com/FluxML/Tracker.jl/blob/642bab12c9b37e7b29fd32925f63cdd9df107df0/src/lib/array.jl#L139), if relevant.

**Comment by CarloLucibello** [comment]
`cumsum` has already been implemented. We can merge the `cumprod` part of this PR if you rebase and fix the formatting issues

**Comment by CarloLucibello** [comment]
this is no longer needed

**Pull request closed without merging**
