### PR TITLE
Fixed bcasting issue on GPU

### PR DESCRIPTION
**Pull request by kshyatt**
Should fix Flux.jl#889 also.

```
julia> using Zygote, CuArrays

julia> v(x, n) = x .^ n;

julia> Zygote.gradient(x -> v(x, 7) |> sum, cu(rand(3,3)))
(Float32[4.804972e-5 0.15564603 7.750634e-6; 0.0015771488 0.6221976 0.32504037; 0.3631478 0.00038040814 0.00063724036],)
```
Also checked this works for `log`.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Awesome, thanks.

Would be great to have a quick test case, even if it's commented out. We're hoping to add GPU CI soon so we could enable it then.

**Comment by kshyatt** [comment]
TFW you're notorious for testing and forget to include a test 😰 . My brand!

Where would be the best place for a test for this?

**Comment by MikeInnes** [comment]
Totally understandable in this case, because it's not easy to add a working test case if we don't have CUDA set up on CI.

I suggest just adding a `cuda.jl` file that can be run manually (doesn't need to be included by `runtests.jl` yet). We can automate it as part of #359.

**Comment by kshyatt** [comment]
Tests added, and I checked that they do pass on the GPU

**Comment by MikeInnes** [comment]
:+1: Thanks!

**Pull request merged**
