### PR TITLE
Add keyword by to adjoint for sort

### PR DESCRIPTION
**Pull request by baggepinnen**

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Can we add a test here that uses a kwargs?

Thanks a lot!

**Comment by baggepinnen** [comment]
added some proper tests for sorting with and without the `by` kwargs

**Comment by dhairyagandhi96** [comment]
Should we just go with the `kwargs...` Notation instead of just `by`, so we can cover the other kwargs too?

**Comment by baggepinnen** [comment]
The PR adding sort argued against that

**Comment by dhairyagandhi96** [comment]
Okay, hopefully it's alright for now.

bors r+

Thanks!

**Pull request merged**
