### PR TITLE
Bump patch

### PR DESCRIPTION
**Pull request by willtebbutt**
As per discussion with @oxinabox on slack.

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Hmm ci seems to be out to lunch.
bors try

**Review by DhairyaLGandhi — APPROVED** [review]

**Comment by willtebbutt** [comment]
@DhairyaLGandhi would you like me to wait until a successful CI run has occured before merging and tagging?

**Comment by DhairyaLGandhi** [comment]
I've retriggered BK, hopefully its alright on 1.5 and we should be good to merge

**Comment by willtebbutt** [comment]
The buildkite failures are weird -- the tests pass, it's seems to fall over after they've completed...

**Comment by DhairyaLGandhi** [comment]
Yeah I wonder if we should remove the coverage to see if that would help. I wouldn't want to remove testing on 1.5 over this esp when the package runs fine. It seems to be when `gc` is triggered. We can also just merge for now and check back later. 

@maleadt did something change in BK?

**Comment by maleadt** [comment]
Yes, cc @DilumAluthge, I'll revert the change.

**Pull request merged**
