### PR TITLE
use IdDict in grad_mut fallback for IdDict

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Fixes hashing issues with CuArrays, i.e. https://github.com/FluxML/Flux.jl/issues/989

### CODE REVIEW

**Comment by CarloLucibello** [comment]
good to go?

**Comment by ChrisRackauckas** [comment]
It should be. I don't see an issue. All it's doing is making things that should've been an IdDict and IdDict.

**Comment by dhairyagandhi96** [comment]
bors try

**Comment by dhairyagandhi96** [comment]
Aside: Ah, found it, bors is syncing from an old state on Zygote. Flux is fine, but I need to figure out how to turn syncing toggle

**Pull request merged**
