### PR TITLE
tag new version

### PR DESCRIPTION
**Pull request by CarloLucibello**

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Does Zygote still give the warning about the CuArrays dependency?

**Comment by CarloLucibello** [comment]
it does, only when testing. Probably having a compact entry for an extras dependency is not kosher. Should I remove it?

**Comment by dhairyagandhi96** [comment]
Correct, yes please

**Comment by dhairyagandhi96** [comment]
Registering it now

**Pull request merged**
