### PR TITLE
Nograd Factorial

### PR DESCRIPTION
**Pull request by jessebett**
Discussed in #109 @willtebbutt suggested `@nograd` for `factorial`

### CODE REVIEW

**Comment by willtebbutt** [comment]
Thanks for doing this @jessebett . Could you please add a quick test to `test/gradcheck.jl` to ensure that we don't accidentally revert this at some point?

**Comment by Keno** [comment]
Would it make sense to instead use the derivative of the Gamma function here?

**Comment by willtebbutt** [comment]
Hmm... is the Gamma function the unique extension of factorial to the reals, or are there other choices?

**Comment by devmotion** [comment]
One needs at least the three properties stated in the [Bohr-Mollerup theorem](https://en.wikipedia.org/wiki/Bohr%E2%80%93Mollerup_theorem): `f(1) = 1`, `f(x + 1) = x f(x)` for `x > 0`, and `f` being logarithmically convex.

**Comment by CarloLucibello** [comment]
we have 
```
@non_differentiable factorial(n::Integer)
```
in ChainRules.jl now

**Pull request closed without merging**
