### PR TITLE
Add PyCall custom @adjoint test

### PR DESCRIPTION
**Pull request by samuela**
Add a test for https://github.com/FluxML/Zygote.jl/issues/789. This test is actually currently failing on master.

### CODE REVIEW

**Comment by samuela** [comment]
The error is
```
PyCall custom @adjoint: Error During Test at /home/samuela/dev/Zygote.jl/test/features.jl:393
  Got exception outside of a @test
  Compiling Tuple{typeof(convert),Type{PyCall.PyAny},PyCall.PyObject}: ArgumentError: array must be non-empty
  Stacktrace:
   [1] pop! at ./array.jl:1147 [inlined]
   [2] ssa!(::IRTools.Inner.IR) at /home/samuela/.julia/packages/IRTools/GVPoj/src/passes/passes.jl:255
   [3] IRTools.Inner.IR(::IRTools.Inner.Meta; slots::Bool, prune::Bool) at /home/samuela/.julia/packages/IRTools/GVPoj/src/ir/wrap.jl:117
   [4] IR at /home/samuela/.julia/packages/IRTools/GVPoj/src/ir/wrap.jl:115 [inlined]
   [5] _lookup_grad(::Type{T} where T) at /home/samuela/dev/Zygote.jl/src/compiler/emit.jl:101
   [6] #s2789#1235 at /home/samuela/dev/Zygote.jl/src/compiler/interface2.jl:39 [inlined]
   [7] #s2789#1235(::Any, ::Any, ::Any) at ./none:0
   [8] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:527
   [9] #_#117 at /home/samuela/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:86 [inlined]
   [10] (::typeof(∂(#_#117)))(::Float64) at /home/samuela/dev/Zygote.jl/src/compiler/interface2.jl:0
   [11] (::Zygote.var"#145#146"{typeof(∂(#_#117)),Tuple{Tuple{Nothing,Nothing},Tuple{Nothing}}})(::Float64) at /home/samuela/dev/Zygote.jl/src/lib/lib.jl:175
   [12] #1681#back at /home/samuela/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49 [inlined]
   [13] PyObject at /home/samuela/.julia/packages/PyCall/zqDXB/src/pyfncall.jl:86 [inlined]
   [14] (::typeof(∂(λ)))(::Float64) at /home/samuela/dev/Zygote.jl/src/compiler/interface2.jl:0
   [15] (::Zygote.var"#41#42"{typeof(∂(λ))})(::Float64) at /home/samuela/dev/Zygote.jl/src/compiler/interface.jl:45
   [16] gradient(::PyCall.PyObject, ::Float64) at /home/samuela/dev/Zygote.jl/src/compiler/interface.jl:54
   [17] top-level scope at show.jl:641
   [18] top-level scope at /home/samuela/dev/Zygote.jl/test/features.jl:400
   [19] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115
   [20] top-level scope at /home/samuela/dev/Zygote.jl/test/features.jl:394
   [21] include(::String) at ./client.jl:457
   [22] top-level scope at /home/samuela/dev/Zygote.jl/test/runtests.jl:19
   [23] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115
   [24] top-level scope at /home/samuela/dev/Zygote.jl/test/runtests.jl:19
   [25] include(::String) at ./client.jl:457
   [26] top-level scope at none:6
   [27] eval(::Module, ::Any) at ./boot.jl:331
   [28] exec_options(::Base.JLOptions) at ./client.jl:272
   [29] _start() at ./client.jl:506
```

**Comment by samuela** [comment]
Jk, I was being a ding dong and had a typo in the test. Test passes now.

**Comment by samuela** [comment]
friendly ping on this

**Comment by CarloLucibello** [comment]
Thanks for this

bors r+

**Comment by samuela** [comment]
CI error appears to be that the "backsolve" and "cholesky" tests are broken: https://gitlab.com/JuliaGPU/Zygote-jl/-/jobs/784331521#L394. Appears to be unrelated to this pr.

**Comment by CarloLucibello** [comment]
closing in favor of #1363

**Pull request closed without merging**
