### PR TITLE
update the version of IRTools in compat

### PR DESCRIPTION
**Pull request by findmyway**

### CODE REVIEW

**Comment by MikeInnes** [comment]
Thanks – on your way, I think we may as well use the release of IRTools, rather than master.

**Comment by findmyway** [comment]
Right, now updated.

**Comment by MikeInnes** [comment]
Looks like the Travis build is failing, any idea if the manifest changes could have caused that?

**Comment by findmyway** [comment]
investigating

**Comment by findmyway** [comment]
The Travis build is passed now. Only the dependencies of `ITRools`  are updated.

However, it still seems very weird to me. If I just run `] up`, the `CUDAapi` seems downgraded to an old version, which caused the `has_cuda` not found [error](https://travis-ci.org/FluxML/Zygote.jl/jobs/601818138?utm_medium=notification&utm_source=github_status).

**Comment by MikeInnes** [comment]
Thanks for looking into that. We can figure out the CUDA issue if it comes up again.

**Pull request merged**
