### PR TITLE
Fix \ for Cholesky

### PR DESCRIPTION
**Pull request by devmotion**
This PR fixes https://github.com/FluxML/Zygote.jl/issues/932 and includes the MWE mentioned in the issue.

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Lgtm, thanks

**Comment by devmotion** [comment]
I also checked that the test fails on master with the error message reported in the issue.

**Comment by willtebbutt** [comment]
This looks great. Could you bump the patch please?

**Comment by DhairyaLGandhi** [comment]
I'll take care of that

bors r+

**Pull request merged**
