### PR TITLE
Bump patch

### PR DESCRIPTION
**Pull request by willtebbutt**
Looks like a patch was skipped when #844 was merged.

### CODE REVIEW

**Review by DhairyaLGandhi — APPROVED** [review]

**Comment by DhairyaLGandhi** [comment]
Is this meant to tag a breeding release

**Comment by willtebbutt** [comment]
Oh, wait, no. It appears that the `Project.toml` was just bumped to 0.6.0. Not sure when / how that happened as I can't see the corresponding PR.

**Comment by willtebbutt** [comment]
Oh, looks like I just missed [this](https://github.com/FluxML/Zygote.jl/pull/824) being merged in.

**Comment by CarloLucibello** [comment]
we didn't even tag v0.6 yet, and we have a few PRs to merge before that  https://github.com/FluxML/Zygote.jl/milestone/2

**Comment by willtebbutt** [comment]
> we didn't even tag v0.6 yet, and we have a few PRs to merge before that https://github.com/FluxML/Zygote.jl/milestone/2

Yup, I've now seen that. Could you maybe branch this stuff out into a 0.6-DEV branch or something so that non-breaking changes to 0.5 aren't blocked?

**Comment by willtebbutt** [comment]
Closing for now. Looks like my merged code will get included in 0.6, which is fine.

**Pull request closed without merging**
