### PR TITLE
Widen type constraints in accum method for tuples

### PR DESCRIPTION
**Pull request by AzamatB**
Fixes [#399](https://github.com/FluxML/Zygote.jl/issues/399)

### CODE REVIEW

**Comment by CarloLucibello** [comment]
it would be nice to add a test here if #399 is easy to reduce

**Comment by MikeInnes** [comment]
Thanks for this fix. I think it's worth some time to make sure it's the right fix – it seems fishy to me that a tuple gradient is being produced here, do you know where that's coming from? We might be able to just fix that gradient definition instead.

**Comment by AzamatB** [comment]
So... With this fix, the gradient for the case when input is a `Vector` of `Matrix`es seems to be different from the case when the input is `Tuple` of `Matrix`es, which is problematic and I have no idea why this is happening... Here is the (not so) minimum reproducible example:
```Julia
using Flux
using Zygote
using LinearAlgebra

mutable struct State
   context
   decoding
   prediction
end

m = (state = State(zeros(Float32, 8, 7), zeros(Float32, 8, 7), zeros(Float32, 4, 7)),
     listen = RNN(5, 8),
     attention_ϕ = Dense(8, 8),
     attention_ψ = Dense(8, 8),
     spell = RNN(20, 8),
     infer = Chain(Dense(16, 4), logsoftmax))

function reset!(m::NamedTuple{(:state, :listen, :attention_ϕ, :attention_ψ, :spell, :infer)})
   m.state.context    = zeros(Float32, 8, 7)
   m.state.decoding   = zeros(Float32, 8, 7)
   m.state.prediction = zeros(Float32, 4, 7)
   Flux.reset!(m.listen)
   Flux.reset!(m.spell)
   return nothing
end

function f(xs)
   hs = m.listen.(xs)
   Hs = cat(hs...; dims=3)
   ψHs = m.attention_ψ.(hs)

   ŷs = map(1:length(xs)) do _
      ϕSᵢᵀ = permutedims(m.attention_ϕ(m.state.decoding))
      Eᵢs = diag.((ϕSᵢᵀ,) .* ψHs)
      αᵢs = softmax(hcat(Eᵢs...)')
      m.state.context = dropdims(sum(reshape(αᵢs, 1, 7, :) .* Hs; dims=3); dims=3)
      m.state.prediction = m.infer([m.state.decoding; m.state.context])
      m.state.decoding = m.spell([m.state.decoding; m.state.prediction; m.state.context])
      return sum(m.state.prediction)
   end
   return sum(ŷs)
end
```
```Julia
julia> xs = [rand(Float32, 5,7) for _ ∈ 1:3]; ts = (xs...,)
(Float32[0.43196976 0.772352 … 0.5282198 0.65421367; 0.8028122 0.6553227 … 0.87582934 0.93192875; … ; 0.53448534 0.7224364 … 0.59748995 0.87444293; 0.24124503 0.62914634 … 0.7682382 0.84297585], Float32[0.7458129 0.84225976 … 0.40603113 0.63792753; 0.20288825 0.7955476 … 0.7162198 0.31203663; … ; 0.9930475 0.2185167 … 0.27938187 0.90089905; 0.06693065 0.7324184 … 0.15423036 0.39481938], Float32[0.62402785 0.90974236 … 0.6624125 0.14417374; 0.6970662 0.99889886 … 0.4307487 0.24024415; … ; 0.3525678 0.8454344 … 0.883291 0.43780363; 0.8516604 0.9982977 … 0.15416789 0.67472076])

julia> reset!(m); Zygote.gradient(f, ts)
((Float32[-0.2776576 -0.21440358 … -0.41327783 0.014859562; 1.4307134 0.5532522 … 0.7604972 0.83826464; … ; 0.17216219 0.48499355 … 0.40543553 0.44233978; -0.6206546 0.19171652 … 0.2179908 -0.10466385], Float32[-0.5593236 -0.31237745 … -0.1291718 -0.50991976; 0.73154306 0.8026974 … 0.6076359 0.7678272; … ; 0.47064045 -0.14150509 … 0.058567703 0.10013718; 0.19204664 0.05327342 … -0.08272661 0.33727422], Float32[-0.26163223 -0.16830444 … -0.15871596 -0.3659225; 0.33024523 0.34587154 … 0.20442791 0.31825042; … ; 0.20989507 0.35989043 … 0.20978197 0.3143729; 0.32453275 0.46157917 … 0.23965813 0.506939]),)

julia> reset!(m); Zygote.gradient(f, xs)
(Array{Float32,2}[[-0.18865515 -0.25170615 … -0.5203248 0.059176438; 0.37795022 0.26160285 … 0.34883058 0.20603119; … ; 0.34578517 0.2099466 … 0.163175 0.3502313; 0.40981013 0.37622443 … 0.6026038 0.2664987], [-1.1587998 -0.81847954 … -0.7162986 -0.9418829; 3.5260978 3.9936826 … 4.423265 3.2079508; … ; -0.749759 -1.4668195 … -1.3134294 -1.3205473; -2.4584074 -1.7757689 … -2.7411826 -0.92188406], [0.2285549 0.10366098 … 0.23647885 -0.2737461; 1.0255145 0.7693287 … 0.89903283 0.5187264; … ; 1.3156765 1.4870335 … 1.1005926 1.8454028; -2.3910856 -1.1765816 … -2.001027 0.26339847]],)
```

@MikeInnes could you give me a direction here where to dig to push this over the line?

**Comment by MikeInnes** [comment]
I think it would be best to narrow down where the original issue is coming from first; I think the right fix would be there rather than here, avoiding this issue.

**Comment by AzamatB** [comment]
@MikeInnes I was able to reduce the original issue down to `gradient(x -> vcat(x...)'x, rand(2))`, so will close this PR and the discussion can continue on that issue (#399).

**Pull request closed without merging**
