### PR TITLE
In-place broadcast over buffers

### PR DESCRIPTION
**Pull request by MikeInnes**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This PR breaks DiffEqSensitivity#zygote in a funny way where it no longer works within functions, but pulling the example out is fine:

```julia
using DiffEqSensitivity,OrdinaryDiffEq
using Test

function f(du,u,p,t)
  du[1] = dx = p[1]*u[1] - p[2]*u[1]*u[2]
  du[2] = dy = -p[3]*u[2] + p[4]*u[1]*u[2]
end

p = [1.5,1.0,3.0,1.0]
prob = ODEProblem(f,[1.0;1.0],(0.0,10.0),p)
sol = solve(prob,Tsit5(),abstol=1e-14,reltol=1e-14)

# g(t,u,i) = (1-u)^2/2, L2 away from 1
function dg(out,u,p,t,i)
  (out.=2.0.-u)
end

easy_res = adjoint_sensitivities(sol,Tsit5(),dg,0.0:0.5:10.0,abstol=1e-14,
                                 reltol=1e-14,iabstol=1e-14,ireltol=1e-12)

# Errors, but did @show to get the values of the expression that failed.
(y, p, λ, t) = ([1.02634, 0.909691], [1.5, 1.0, 3.0, 1.0], [0.973655, 1.09031], 10.0)

# Now copy-paste and run the same function in the REPL
using Zygote
zyg_f = u -> begin
 out_ = Zygote.Buffer(u)
 f(out_, u, p, t)
 copy(out_)
end
_dy, back = Zygote.pullback(zyg_f,y)
@show y, p, λ, t
vec(back(λ)[1])

# It works!
```

This test passes on Zygote#master

**Comment by ChrisRackauckas** [comment]
FWIW, the case that this branch was supposed to fix also has the same error:

```julia
f = (du, u, p, t) -> du .= 0
p = zeros(3); u = zeros(50)
prob = ODEProblem(f,u,(0.0,10.0),p)
sol = solve(prob,Tsit5(),abstol=1e-14,reltol=1e-14)
@test_nowarn res = adjoint_sensitivities(sol,Tsit5(),dg,t,abstol=1e-14,
                                 reltol=1e-14,iabstol=1e-14,ireltol=1e-12)
```

```
MethodError: no method matching vec(::Nothing)
Closest candidates are:
  vec(!Matched::Transpose{T,#s623} where #s623<:(AbstractArray{T,1} where T) where T) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\adjtrans.jl:153
  vec(!Matched::SparseArrays.AbstractSparseArray{Tv,Ti,1} where Ti where Tv) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\SparseArrays\src\sparsevector.jl:901
  vec(!Matched::StaticArrays.StaticArray) at C:\Users\accou\.julia\packages\StaticArrays\3KEjZ\src\abstractarray.jl:159
  ...
(::DiffEqSensitivity.ODEAdjointSensitivityFunction{Array{Float64,1},Array{Float64,1},Array{Float64,1},Nothing,Nothing,Nothing,Nothing,Nothing,SensitivityAlg{0,true,Val{:central}},Nothing,Nothing,Nothing,Nothing,Array{Float64,1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},ODEFunction{true,getfield(Main, Symbol("##9#10")),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{true,getfield(Main, Symbol("##9#10")),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},DiffEqBase.DEStats},Nothing,Nothing})(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64) at adjoint_sensitivity.jl:152
ODEFunction at diffeqfunction.jl:230 [inlined]
initialize!(::OrdinaryDiffEq.ODEIntegrator{Tsit5,true,Array{Float64,1},Float64,Array{Float64,1},Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},ODEFunction{true,DiffEqSensitivity.ODEAdjointSensitivityFunction{Array{Float64,1},Array{Float64,1},Array{Float64,1},Nothing,Nothing,Nothing,Nothing,Nothing,SensitivityAlg{0,true,Val{:central}},Nothing,Nothing,Nothing,Nothing,Array{Float64,1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},ODEFunction{true,getfield(Main, Symbol("##9#10")),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{true,getfield(Main, Symbol("##9#10")),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},DiffEqBase.DEStats},Nothing,Nothing},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Symbol,CallbackSet{Tuple{},Tuple{DiscreteCallback{getfield(DiffEqCallbacks, Symbol("##33#36")){Base.RefValue{Union{Nothing, Float64}}},getfield(DiffEqCallbacks, Symbol("##34#37")){getfield(DiffEqSensitivity, Symbol("#time_choice#20")){StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Base.RefValue{Int64}},getfield(DiffEqSensitivity, Symbol("##19#21")){typeof(dg),Bool,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Array{Float64,1},Base.RefValue{Int64},Int64},Base.RefValue{Union{Nothing, Float64}}},getfield(DiffEqCallbacks, Symbol("##35#38")){typeof(DiffEqBase.INITIALIZE_DEFAULT),Bool,getfield(DiffEqSensitivity, Symbol("#time_choice#20")){StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Base.RefValue{Int64}},Base.RefValue{Union{Nothing, Float64}},getfield(DiffEqCallbacks, Symbol("##34#37")){getfield(DiffEqSensitivity, Symbol("#time_choice#20")){StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Base.RefValue{Int64}},getfield(DiffEqSensitivity, Symbol("##19#21")){typeof(dg),Bool,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Array{Float64,1},Base.RefValue{Int64},Int64},Base.RefValue{Union{Nothing, Float64}}}}}}},Tuple{Symbol},NamedTuple{(:callback,),Tuple{CallbackSet{Tuple{},Tuple{DiscreteCallback{getfield(DiffEqCallbacks, Symbol("##33#36")){Base.RefValue{Union{Nothing, Float64}}},getfield(DiffEqCallbacks, Symbol("##34#37")){getfield(DiffEqSensitivity, Symbol("#time_choice#20")){StepRangeLen{Float64,Base.Twic...
```

**Comment by MikeInnes** [comment]
That's just due to a splatting bug that was fixed a couple of days ago (#358).

The "calling context" has nothing to do with, except that you used a different function (`f`) in your test case, instead of the DiffEq-generated wrapper for `f`. With that change the bug reproduces perfectly well.

**Comment by ChrisRackauckas** [comment]
I see, when rebased onto master that issue goes away.

Now it's just an issue with actually using this branch.

```julia
f = (du, u, p, t) -> du .= 0
p = zeros(3); u = zeros(50)
prob = ODEProblem(f,u,(0.0,10.0),p)
sol = solve(prob,Tsit5(),abstol=1e-14,reltol=1e-14)
@test_nowarn res = adjoint_sensitivities(sol,Tsit5(),dg,t,abstol=1e-14,
                                 reltol=1e-14,iabstol=1e-14,ireltol=1e-12)
```

Gives:

```julia
Need an adjoint for constructor Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Tuple{Base.OneTo{Int64}},typeof(identity),Tuple{Int64}}. Gradient is of type Array{Float64,1}
error(::String) at error.jl:33
(::Zygote.Jnew{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Tuple{Base.OneTo{Int64}},typeof(identity),Tuple{Int64}},Nothing,false})(::Array{Float64,1}) at lib.jl:255
(::getfield(Zygote, Symbol("##319#back#162")){Zygote.Jnew{Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Tuple{Base.OneTo{Int64}},typeof(identity),Tuple{Int64}},Nothing,false}})(::Array{Float64,1}) at adjoint.jl:49
Type at broadcast.jl:170 [inlined]
(::typeof(∂(Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Tuple{Base.OneTo{Int64}},typeof(identity),Tuple{Int64}})))(::Array{Float64,1}) at interface2.jl:0
Type at broadcast.jl:179 [inlined]
(::typeof(∂(Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Axes,F,Args} where Args<:Tuple where F where Axes)))(::Array{Float64,1}) at interface2.jl:0
Type at broadcast.jl:175 [inlined]
(::typeof(∂(Base.Broadcast.Broadcasted)))(::Array{Float64,1}) at interface2.jl:0
materialize! at broadcast.jl:759 [inlined]
#19 at adjoint.jl:159 [inlined]
(::typeof(∂(getfield(Main, Symbol("##19#20"))())))(::Nothing) at interface2.jl:0
#143 at lib.jl:134 [inlined]
#286#back at adjoint.jl:49 [inlined]
ODEFunction at diffeqfunction.jl:230 [inlined]
(::typeof(∂(λ)))(::Nothing) at interface2.jl:0
#13 at adjoint_sensitivity.jl:146 [inlined]
(::typeof(∂(λ)))(::Array{Float64,1}) at interface2.jl:0
#28 at interface.jl:38 [inlined]
(::DiffEqSensitivity.ODEAdjointSensitivityFunction{Array{Float64,1},Array{Float64,1},Array{Float64,1},Nothing,Nothing,Nothing,Nothing,Nothing,SensitivityAlg{0,true,Val{:central}},Nothing,Nothing,Nothing,Nothing,Array{Float64,1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},ODEFunction{true,getfield(Main, Symbol("##19#20")),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{true,getfield(Main, Symbol("##19#20")),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},DiffEqBase.DEStats},Nothing,Nothing})(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64) at adjoint_sensitivity.jl:152
ODEFunction at diffeqfunction.jl:230 [inlined]
initialize!(::OrdinaryDiffEq.ODEIntegrator{Tsit5,true,Array{Float64,1},Float64,Array{Float64,1},Float64,Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},ODEFunction{true,DiffEqSensitivity.ODEAdjointSensitivityFunction{Array{Float64,1},Array{Float64,1},Array{Float64,1},Nothing,Nothing,Nothing,Nothing,Nothing,SensitivityAlg{0,true,Val{:central}},Nothing,Nothing,Nothing,Nothing,Array{Float64,1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},ODEFunction{true,getfield(Main, Symbol("##19#20")),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{true,getfield(Main, Symbol("##19#20")),UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},DiffEqBase.DEStats},Nothing,Nothing},UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Symbol,CallbackSet{Tuple{},Tuple{DiscreteCallback{getfield(DiffEqCallbacks, Symbol("##33#36")){Base.RefValue{Union{Nothing, Float64}}},getfield(DiffEqCallbacks, Symbol("##34#37")){getfield(DiffEqSensitivity, Symbol("#time_choice#20")){StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Base.RefValue{Int64}},getfield(DiffEqSensitivity, Symbol("##19#21")){typeof(dg),Bool,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}},Array{Float64,1},Base.RefValue{Int64},Int64},Base.RefValue{Union{Nothing, Float64}}},getfield(DiffEq...
```

It seems that whatever is normally done for broadcast constructor handling isn't done when it's a Zygote.Buffer.

**Comment by MikeInnes** [comment]
That looks a lot like another test case where I'm going to have to debug through all of DiffEq to figure out what's going on. Please make it more minimal (with care about which variables you are using).

**Comment by ChrisRackauckas** [comment]
MWE: 

```julia
using Zygote, OrdinaryDiffEq
f = (du, u, p, t) -> du .= 0
p = zeros(3); u = zeros(50)
prob = ODEProblem(f,u,(0.0,10.0),p)
sol = solve(prob,Tsit5(),abstol=1e-14,reltol=1e-14)
t = 0.0:0.5:10.0 # TODO: Add end point handling for callback
# g(t,u,i) = (1-u)^2/2, L2 away from 1
function dg(out,u,p,t,i)
  (out.=2.0.-u)
end

(y, p, λ, t) = ([1.02634, 0.909691], [1.5, 1.0, 3.0, 1.0], [0.973655, 1.09031], 10.0)
_dy, back = Zygote.pullback(y) do u
  if DiffEqBase.isinplace(sol.prob)
    out_ = Zygote.Buffer(u)
    f(out_, u, p, t)
    copy(out_)
  else
    vec(f(u, p, t))
  end
end
dλ[:] = vec(back(λ)[1])
```

**Comment by MikeInnes** [comment]
We have different notions of what "minimal" means, I think.

**Comment by ChrisRackauckas** [comment]
```julia
using Zygote
f = (du, u, p, t) -> du .= 0
(y, p, λ, t) = ([1.02634, 0.909691], [1.5, 1.0, 3.0, 1.0], [0.973655, 1.09031], 10.0)
_dy, back = Zygote.pullback(y) do u
  out_ = Zygote.Buffer(u)
  f(out_, u, p, t)
  copy(out_)
end
dλ[:] = vec(back(λ)[1])
```

**Comment by MikeInnes** [comment]
Nearly there.

**Pull request merged**
