### PR TITLE
Fix adjoint for Symmetric and add Hermitian

### PR DESCRIPTION
**Pull request by sdaxen**
The current adjoint for `Symmetric` assumes `uplo=:U` and gives the wrong adjoint for complex symmetric matrices (it uses `adjoint` where it should use `transpose`).

This PR fixes the above issues and also adds the adjoint for `Hermitian`.

### CODE REVIEW

**Comment by sdaxen** [comment]
Can anyone shed light on the errors in the type hacks version for Julia 1.3 and nightly? Example: https://travis-ci.org/FluxML/Zygote.jl/jobs/590137457#L251-L256, which refers to this line of code:
https://github.com/FluxML/Zygote.jl/blob/4f49dc91938adb981862fb98bfcf488a3bd93b02/test/gradcheck.jl#L351

**Comment by willtebbutt** [comment]
Really nice work. I'm happy for this to be merged once tests pass

**Comment by sdaxen** [comment]
Alright, looks good to me now.

**Comment by sdaxen** [comment]
Is there anything preventing this being merged? I've got another PR in the works that depends on it.

**Pull request merged**
