### PR TITLE
Taylor Series

### PR DESCRIPTION
**Pull request by MikeInnes**
Addressing #130.

```julia
using Zygote, TaylorSeries
using Zygote: taylor, derive

gradient(5, 3) do x, n
  x, n = taylor(x), taylor(n)
  x = x + Taylor1(10)
  y = x*n
  derive(y, 1)
end # (0, 1)
```

`derive(y, n)` gets the derivative `d^n y / dx^n`, and then we take the gradient of `x` and `n` with respect to that. It's a bit clunky right now; in particular, anything you want gradients for, you have to call `taylor` on it before using it. So it's not totally automated when it comes to e.g. running this through a Flux model, though this can still be done with `destructure` and `restructure` as in DiffEqFlux.

We can also differentiate against many orders at once:

```julia
gradient(3) do n
  n = taylor(n)
  x = 1 + Taylor1(10)
  y = sin(x+n)
  sum(derive(y, i) for i = 1:10)
end # 1.41
```

TaylorSeries is accurate and instantaneous even up to about 100th order.

Hoping @jessebett can play around with this and get something more realistic working.

### CODE REVIEW

**Comment by jessebett** [comment]
`derive` means take nth order derivatives with TaylorSeries method? I think that should be clearly named something like `taylordiff`

**Comment by jessebett** [comment]
Also, not the biggest fan of `n=taylor(n)`.  This confuses where the taylor expansion actually is. For example, in your above code you have 
```
n = taylor(n)
x = 1 + Taylor1(10)
```

So it should be clear that the higher order taylor terms are for x. So it's not clear what `taylor(n)` is doing, right? This should be very clear because otherwise what variable is `derive(y,1)` wrt? It's the variable in the TaylorSeries expansion for x, but having `taylor(n)` makes this ambiguous.

**Comment by MikeInnes** [comment]
Yeah, the interface is not great right now. The right way to do this would clearly be `taylordiff(f, x)`, and then we could even do things like automatically handling the vector `x` case.

The technical reason for this is that the adjoint of `derive` is not a normal value but a `TaylorAdjoint` that stores the derivative at multiple orders. At some point we have to reduce that `TaylorAdjoint` back to a normal value; currently there's no obvious place to do that unless you ask for it via `taylor`.

**Comment by jessebett** [comment]
Possibly my issue is that I'm not sure where `taylor` is supposed to go. But gradients through basic operations with `Taylor1` are still failing

```
θ = taylor(5.)
f(x) = x .* θ
x = Taylor1(1.,3)
f(x)
gradient(()->f(x)[0],Params([θ]))
```

This currently returns `ERROR: ArgumentError: broadcasting over dictionaries and `NamedTuple`s is reserved`

**Comment by jessebett** [comment]
```
θ = taylor(5.)
f(t,z) = θ .* t.^5 + z
x = taylor(1.)
t = shift_taylor(0,10)
f(t,x)
derive(f(t,x),5)
gradient(()->derive(f(t,x),5),Params([θ]))
```

This returns `ERROR: MethodError: no method matching length(::Zygote.TaylorAdjoint{Int8})`

**Comment by MikeInnes** [comment]
`taylor` needs to be part of the forward pass, since it does its work during the backwards pass. Here's a working version:

```julia
using Zygote, TaylorSeries
using Zygote: taylor, derive

shift_taylor(x,n) = x + Taylor1(typeof(x),n)

θ = [5.]

f(t,z) = taylor(θ[]) .* t.*5.0 + z

x = 1.
t = shift_taylor(0,10)
f(t,x)
derive(f(t,x),5)

gs = gradient(()->derive(f(t,x),5),Params([θ]))
gs[θ]
```

Unfortunately this fails with `t^5` due to us trying to call `log` of a `0` taylor series in the backwards pass. If you need that particular operation we'll have to work around that some how.

**Comment by MikeInnes** [comment]
Closing this for now as I think we want something more general for this to be worthwhile.

**Pull request closed without merging**
