### PR TITLE
FillArray broadcasting functionality

### PR DESCRIPTION
**Pull request by willtebbutt**
Functionality to ensure that broadcasting works properly with `AbstractFill`s.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Not that nice to have to list out all these case (though it may be necessary of course). Do things break without these, or is it just slow, or something else?

**Comment by willtebbutt** [comment]
That's a fair point. Last time I tried to do things without them they just broke. Will see what happens if they're not there and get back to you.

**Comment by willtebbutt** [comment]
Turns out that we don't need most of the definitions. One was required to ensure that the adjoint is a `Fill` when appropriate, but other than that it appears to be fine. So this PR now just looks like a large number of tests, which isn't a terrible thing I guess.

**Comment by MikeInnes** [comment]
Cool. Yep, that looks good to me then.

**Pull request merged**
