### PR TITLE
Make Cholesky adjoint GPU-friendly

### PR DESCRIPTION
**Pull request by aterenin**
This PR modifies the Cholesky adjoint to replace loop with broadcast, which makes it work on GPU once appropriate low-level linear algebra methods are available. I'm making a number of PRs for these (for example: https://github.com/JuliaGPU/GPUArrays.jl/pull/262).

### CODE REVIEW

**Comment by CarloLucibello** [comment]
this can be merged right now irrespective of the GPUArrays changes, right?
Then once your other PR is merged and gpuarrays tagged it would be nice if you could file another PR testing this on gpu

**Comment by aterenin** [comment]
Yes, this can be merged now. For GPU, it needs other PRs for `mul!` and `trsm!` which I will make soon once other PRs get merged in.

**Comment by CarloLucibello** [comment]
what about using non-mutating operations? is `BLAS.trsm` supported right now?

**Comment by aterenin** [comment]
Not yet. The CUBLAS versions are all available from `CuArrays.CUBLAS`, but have a very slightly different API from BLAS (for instance, CUBLAS `trsm!` allows non-in-place, whereas BLAS `trsm!` is in-place only). This means that wrappers are needed to translate between these - will be making a PR with these soon.

**Comment by CarloLucibello** [comment]
ok, let's merge this then

bors r+

**Pull request merged**
