### PR TITLE
Canonicalize the Composite before changing it to a NamedTuple

### LINKED ISSUE #922: accumulation of gradients
The issue occurs when the following are all true:

- We have a struct with two differentiable fields
- We need to accumulate the gradients with respect to both fields
- The gradients that need to be accumulated both originate from an rrule

An example is svd factorisation:

```julia
using Zygote
using LinearAlgebra
using FiniteDifferences
using Test

# function to test AD against finite differences. Can't wait for https://github.com/JuliaDiff/ChainRulesTestUtils.jl/issues/114
function test_ad(test_function, Δoutput, inputs...; atol=1e-7, rtol=1e-7)
    # Verify that the forwards-pass produces the correct answer.
    output, pb = Zygote.pullback(test_function, inputs...)
    @test output ≈ test_function(inputs...)

    # Compute the adjoints using AD and FiniteDifferences.
    dW_ad = pb(Δoutput)
    dW_fd = FiniteDifferences.j′vp(central_fdm(5, 1), test_function, Δoutput, inputs...)

    # Compare AD and FiniteDifferences results.
    @testset "$(typeof(test_function)) argument $n" for n in eachindex(inputs)
        @test dW_ad[n] ≈ dW_fd[n] atol=atol rtol=rtol
    end
end

function two_svds(X::StridedMatrix{<:Union{Real, Complex}})
    return svd(X).U * svd(X).V'
end

function one_svd(X::StridedMatrix{<:Union{Real, Complex}})
    F = svd(X)
    return F.U * F.V'
end

Δoutput = randn(3,2)
X = randn(3,2)

test_ad(two_svds, Δoutput, X) # works

test_ad(one_svd, Δoutput, X) # fails

  Expression: ≈(dW_ad[n], dW_fd[n], atol = atol, rtol = rtol)
   Evaluated: [0.10086994903629046 0.017821972969422787; -0.025950275563480844 -0.20012541965315742; 0.1827211721197507 0.16897788019829582] ≈ [-1.5134220464481536 -1.9386355487247564; 0.4546889986237118 0.8662734137317394; 0.9222144395826724 1.4004778288991626] (atol=1.0e-7, rtol=1.0e-7)

```

I think the reason is that the accumulation of gradients is not defined for `literal_getproperty`, just `literal_getfield`
https://github.com/FluxML/Zygote.jl/blob/890b6f57303fb983a815aec5fea92620c93a4bd3/src/lib/lib.jl#L213-L226

Will submit a PR later today

### PR DESCRIPTION
**Pull request by mzgubic**
Closes #922.

The issue occurs when the following are all true:
1) We have a struct with two differentiable fields
2) We need to accumulate the gradients with respect to both fields
3) The gradients that need to be accumulated both originate from an rrule

In that case, the two gradients that originate from an rrule are `Composite`s with disjoint fields. When they are transformed to a `NamedTuple`, the Zygote internal representation of derivatives w.r.t. structs, these two `NamedTuple`s have disjoint sets of keys, and are not `accum`ulated correctly.

By adding `canonicalize(x)`, the `Composite` gets explicit `Zero()` fields, which means the resulting `NamedTuple`s have the complete set of fields. 

~~- blocked by https://github.com/JuliaDiff/ChainRules.jl/pull/390 (tests only)~~
~~- need to change compat once the above is merged~~

### CODE REVIEW

**Comment by mzgubic** [comment]
Looks like we either need https://github.com/JuliaDiff/ChainRulesCore.jl/issues/321 or use 
```julia
    maybe_canonicalized = isabstracttype(P) ? x : canonicalize(x)
    xp = map(wrap_chainrules_output, maybe_canonicalized)
```
instead. It seems to be able to do type inference alright.

**Comment by DhairyaLGandhi** [comment]
Seems a bit hairy. Could you give me an idea of what `canonicalize` does concretely?

**Comment by mzgubic** [comment]
Yeah I'd prefer the issue but there might be reasons not to do that (I can't think of any, but there might be).

To understand `canonicalize` one needs to know that `Composite`s, which are the differential types for structs, only store non-zero gradients explicitly. For example, if I have a `MyStruct` with two fields, `a` and `b`, then the `rrule` for `getproperty(mystruct, a)` can return `Composite{MyStruct}(;a=ȳ)` rather than `Composite{MyStruct}(;a=ȳ, b=Zero())`.

The zeros for other fields are implicit, meaning it is possible to sum `Composites` easily:
```julia
julia> Composite{MyStruct}(;a=ȳ) + Composite{MyStruct}(;b=ȳ2)
Composite{MyStruct}(;a=ȳ, b=ȳ2)
```

`canonicalize` will simply make these implicit `Zero()`s explicit, i.e. 
```julia
julia> canonicalize(Composite{MyStruct}(;a=ȳ))
Composite{MyStruct}(;a=ȳ, b=Zero())
```

This relies on knowing the primal type (`MyStruct`) that `Composite` stores the derivative for in order to access the fields. Here, the issue is that in higher-order AD sometimes the primal type is unknown*, and in that case it is not possible to know which fields should explicitly be set to zero.

*I _think_ we can get rid of this once Zygote uses ChainRules differential types internally

**Comment by oxinabox** [comment]
I am pretty sure we should do this.
Since otherwise the NamedTuple that comes out of a ChainRules rule will not ensc have the same fields as one from Zygote working it out on its own.
And that will lead to badness.

I commented on this here: https://github.com/FluxML/Zygote.jl/issues/861#issuecomment-750480710

**Review by oxinabox — APPROVED** [review]

**Comment by mzgubic** [comment]
I've added ChainRulesCore as a direct dependency to be able to specify a compat bound. I don't have merge rights but there is nothing I want to add, so please go ahead once you think it's ready

**Comment by oxinabox** [comment]
the GPU tests for o Cholesky weem flaky

See if they work for bores

Bors r+

**Comment by mzgubic** [comment]
Same test failed in a [different PR which only added another test](https://github.com/FluxML/Zygote.jl/pull/925). Not sure what to think about that, but I don't think it's related to either of the PRs?

**Comment by mzgubic** [comment]
Could you try again please?

**Pull request merged**
