### PR TITLE
Use literal_getproperty from ZygoteRules

### PR DESCRIPTION
**Pull request by tkf**
close https://github.com/FluxML/ZygoteRules.jl/issues/3

This RP requires https://github.com/FluxML/ZygoteRules.jl/pull/5 <strike>to be merged and then ZygoteRules 0.2 to be released.</strike>

### CODE REVIEW

**Comment by MikeInnes** [comment]
Would be great if you can update the Zygote manifest to point to the right commit of ZygoteRules, so CI works.

**Comment by tkf** [comment]
Hi, thanks for merging the other PR!  I rebased onto master to reflect the change in manifest and also to resolve the conflict.

**Comment by MikeInnes** [comment]
Would you mind rebasing so CI passes? Then we can merge -- thanks!

**Comment by tkf** [comment]
Rebased and CI is green.

**Comment by MikeInnes** [comment]
:+1: Thanks!

**Pull request merged**
