### PR TITLE
add adjoint for FMA

### LINKED ISSUE #296: fma not supported
```julia
julia> using Zygote

julia> f(x) = fma(x, x, x)
f (generic function with 1 method)

julia> f'(1.0)
ERROR: Non-differentiable function fma_float
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] (::typeof(∂(λ)))(::Float64) at ./none:0
 [3] fma_llvm at ./floatfuncs.jl:309 [inlined]
 [4] (::typeof(∂(fma_llvm)))(::Float64) at /home/tamas/.julia/packages/Zygote/fuj2C/src/compiler/interface2.jl:0
 [5] fma at ./floatfuncs.jl:320 [inlined]
 [6] (::typeof(∂(fma)))(::Float64) at /home/tamas/.julia/packages/Zygote/fuj2C/src/compiler/interface2.jl:0
 [7] f at ./REPL[101]:1 [inlined]
 [8] (::typeof(∂(f)))(::Float64) at /home/tamas/.julia/packages/Zygote/fuj2C/src/compiler/interface2.jl:0
 [9] (::getfield(Zygote, Symbol("##32#33")){typeof(∂(f))})(::Float64) at /home/tamas/.julia/packages/Zygote/fuj2C/src/compiler/interface.jl:38
 [10] gradient(::Function, ::Float64) at /home/tamas/.julia/packages/Zygote/fuj2C/src/compiler/interface.jl:47
 [11] (::getfield(Zygote, Symbol("##34#35")){typeof(f)})(::Float64) at /home/tamas/.julia/packages/Zygote/fuj2C/src/compiler/interface.jl:50
 [12] top-level scope at REPL[106]:1

(v1) pkg> st --manifest Zygote
    Status `~/.julia/environments/v1/Manifest.toml`
  [b552c78f] DiffRules v0.0.10
  [1a297f60] FillArrays v0.5.0
  [f6369f11] ForwardDiff v0.10.3
  [7869d1d1] IRTools v0.2.2
  [1914dd2f] MacroTools v0.5.1
  [872c559c] NNlib v0.6.0
  [77ba4419] NaNMath v0.3.2
  [ae029012] Requires v0.5.2
  [276daf66] SpecialFunctions v0.7.2
  [e88e6eb3] Zygote v0.3.2
  [b77e0a4c] InteractiveUtils 
  [37e2e46d] LinearAlgebra 
  [9a3f8284] Random 
  [10745b16] Statistics 

julia> VERSION
v"1.2.0-rc3.0"
```

### PR DESCRIPTION
**Pull request by tpapp**
Fixes #296.

### CODE REVIEW

**Comment by tpapp** [comment]
I am happy to add tests, just not sure where/how.

**Comment by MikeInnes** [comment]
Thanks. Should be easy to add a check to `gradcheck.jl`, following the others there.

**Comment by MikeInnes** [comment]
:+1: Thanks!

**Comment by tpapp** [comment]
Thanks for your help with this. Would you please consider tagging a patch release? It would make CI easier for me.

**Comment by willtebbutt** [comment]
> Thanks for your help with this. Would you please consider tagging a patch release? It would make CI easier for me.

Seconded. Would very much like the `ZygoteRules` stuff to be tagged so that I can depend on that in Stheno.

**Comment by MikeInnes** [comment]
Patch release is out with https://github.com/JuliaRegistries/General/pull/2782

**Pull request merged**
