### PR TITLE
Cleaner pmap adjoint

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
cc @ChrisRackauckas 

We would need a simple MWE, which should ideally hold something in a local cache maintained by the workers, without serialising them

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
https://github.com/FluxML/Zygote.jl/pull/845 was updated and works correctly. This will stall on the construction of caching pools.

**Comment by DhairyaLGandhi** [comment]
Cool, I'll close this then

**Comment by DhairyaLGandhi** [comment]
Seems like the same diff, we need to make ci catch the stall

**Comment by ChrisRackauckas** [comment]
It just needs to add the caching pull to the call. I'll add that.

**Comment by DhairyaLGandhi** [comment]
To confirm, #845 doesn't stall with the call to CachingPool, right?

**Comment by ChrisRackauckas** [comment]
Yes, you just have to `@nograd` it and the `workers` call, which both shouldn't have Zygote touching.

**Pull request closed without merging**
