### PR TITLE
fix gpu integration tests

### PR DESCRIPTION
**Pull request by CarloLucibello**
bu adding a compat entry for CuArrays

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
We already have an entry in the extras for a test dependency, and we need to be compatible with CuArrays 2 right?

**Comment by CarloLucibello** [comment]
> We already have an entry in the extras for a test dependency, and we need to be compatible with CuArrays 2 right?

sorry adding to deps was a mistake, check now. I'm not updating to cuarrays 2 here, just making sure that test pass as they used to do

**Comment by dhairyagandhi96** [comment]
Even so, this would limit the CuArrays version Flux will be able to use right? An `up` on the environment should have been fine otherwise.

**Comment by CarloLucibello** [comment]
I tried `add Flux#master`  and the compat here doesn't block the installation of cuarrays 2.0 required by flux

**Comment by CarloLucibello** [comment]
@dhairyagandhi96 why you say up the environment? CuArrays is not part of the environment...
You mean we should create a  Manifest.toml in test/?

**Comment by dhairyagandhi96** [comment]
> I tried add Flux#master and the compat here doesn't block the installation of cuarrays 2.0 required by flux

Does that install release Zygote or master?

**Pull request merged**
