### PR TITLE
Gradient for power

### LINKED ISSUE #247: Adjoint of literal_pow fails when grad is calculated on negative input
This error arises due to the fact that `literal_pow` is defined as multiplication for powers : 1, 2, 3 but for higher powers it follows this definition https://github.com/JuliaLang/julia/blob/cef655a68a4e824cbe7cca582256d61aa72eb725/base/intfuncs.jl#L253. Due to which it is trying to calculate gradient with respect to base, as well as gradient with respect to exponent. In the latter case, since the gradient involves log, it fails for negative input.

### LINKED ISSUE #511: Cannot calculate gradient.
I am new to Julia. I am trying to calculate the gradient of a fairly simple function but it is throwing error. 

```
using Zygote
gradient((t1, t2) -> (t1-2)^4 + (t1-2*t2)^2, 0 ,0)
```
The error message is following: 
```
julia> gradient((t1, t2) -> (t1-2)^4 + (t1-2*t2)^2, 0 ,0)
ERROR: DomainError with -2.0:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(::Symbol, ::Float64) at ./math.jl:32
 [2] log(::Float64) at ./special/log.jl:285
 [3] log at ./special/log.jl:395 [inlined]
 [4] #626 at /Users/nilaythakor/.julia/packages/Zygote/tJj2w/src/lib/number.jl:28 [inlined]
 [5] #1659#back at /Users/nilaythakor/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49 [inlined]
 [6] macro expansion at ./none:0 [inlined]
 [7] literal_pow at ./none:0 [inlined]
 [8] #55 at ./none:1 [inlined]
 [9] (::typeof(∂(#55)))(::Int64) at /Users/nilaythakor/.julia/packages/Zygote/tJj2w/src/compiler/interface2.jl:0
 [10] (::Zygote.var"#36#37"{typeof(∂(#55))})(::Int64) at /Users/nilaythakor/.julia/packages/Zygote/tJj2w/src/compiler/interface.jl:38
 [11] gradient(::Function, ::Int64, ::Vararg{Int64,N} where N) at /Users/nilaythakor/.julia/packages/Zygote/tJj2w/src/compiler/interface.jl:47
 [12] top-level scope at none:0

```

### PR DESCRIPTION
**Pull request by mcabbott**
Closes #511, closes #247, and #426.

### CODE REVIEW

**Comment by CarloLucibello** [comment]
what's the problem here? It would be nice to have those issues closed

**Comment by dhairyagandhi96** [comment]
bors try

**Comment by mcabbott** [comment]
Test failure is 
```
Unexpected Pass
250 Expression: gradtest((x->begin
251            prod(x, dims=(2, 3))
252        end), (3, 4, 5))
```
I have no idea why this PR should make that pass, the gradient definition is wrong, and fixed in #112

**Comment by dhairyagandhi96** [comment]
Strangely I did not see the changes to the gradients with #112 but the build does seem to pass on there

**Comment by CarloLucibello** [comment]
let's see if bors promoted me

bors r+

**Comment by CarloLucibello** [comment]
no :(

**Comment by CarloLucibello** [comment]
thanks! this solves very basic issues, we should tag a new release

**Pull request merged**
