### PR TITLE
Fix converting UniformScaling to Matrix

### LINKED ISSUE #468: Converting UniformScaling to Matrix causes mutation
While working on https://github.com/TuringLang/Turing.jl/pull/783, I ran into the following error which I am struggling to understand:
```julia
using LinearAlgebra, Zygote
function f(x)
    cholesky(Matrix{Float64}(I, 4, 4))
    return 1.0
end
Zygote.gradient(f, [1.0])
```
The error is:
```julia
ERROR: Mutating arrays is not supported
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] (::getfield(Zygote, Symbol("##1000#1001")))(::Nothing) at C:\Users\user\.julia\dev\Zygote\src\lib\array.jl:44
 [3] (::getfield(Zygote, Symbol("##2658#back#1002")){getfield(Zygote, Symbol("##1000#1001"))})(::Nothing) at C:\Users\user\.julia\packages\ZygoteRules\6nssF\src\adjoint.jl:49
 [4] Type at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\LinearAlgebra\src\uniformscaling.jl:386 [inlined]
 [5] (::typeof(∂(Array{Float64,2})))(::Nothing) at C:\Users\user\.julia\dev\Zygote\src\compiler\interface2.jl:0
 [6] Type at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\LinearAlgebra\src\uniformscaling.jl:390 [inlined]
 [7] (::typeof(∂(Array{Float64,2})))(::Nothing) at C:\Users\user\.julia\dev\Zygote\src\compiler\interface2.jl:0
 [8] f at .\REPL[2]:2 [inlined]
 [9] (::typeof(∂(f)))(::Float64) at C:\Users\user\.julia\dev\Zygote\src\compiler\interface2.jl:0
 [10] (::getfield(Zygote, Symbol("##28#29")){typeof(∂(f))})(::Float64) at C:\Users\user\.julia\dev\Zygote\src\compiler\interface.jl:38
 [11] gradient(::Function, ::Array{Float64,1}) at C:\Users\user\.julia\dev\Zygote\src\compiler\interface.jl:47
 [12] top-level scope at REPL[6]:1
```
The error is using Zygote master. Any idea how to fix this?

CC: @willtebbutt

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR fixes #468.

### CODE REVIEW

**Comment by mohamed82008** [comment]
How do you use `@nograd` with dispatch and type parameters?

**Comment by CarloLucibello** [comment]
can you add the example from #468 as a test?

**Comment by mohamed82008** [comment]
Sure.

**Comment by willtebbutt** [comment]
LGTM now that there are tests.

Probably not a case for `@nograd` @dhairyagandhi96 as it's not generally the case that `Matrix` should not propagate gradient information.

**Comment by mcabbott** [comment]
Note that `Matrix(I,(2,2))` is also allowed -- perhaps it should just be `@adjoint function Matrix(::UniformScaling, ij...)` etc?

**Comment by mohamed82008** [comment]
Fixed the tuple case.

**Comment by mohamed82008** [comment]
Bump

**Comment by mohamed82008** [comment]
Makes sense, thanks @MikeInnes. I applied your fix and tested it.

**Comment by MikeInnes** [comment]
Wonderful, thanks!

bors r+

**Pull request merged**
