### PR TITLE
A Jacobian which understands Params

### LINKED ISSUE #413: Jacobian in Zygote with Params
I simply love the Flux+Zygote flexibility for extracting parameters from object and get the appropriate gradients directly in the same structure (`Grads`).
However it would be nice to have the same feature for `jacobian`s with `Params`. I saw the already open issues #98 and #51. But the proposed workaround is only valid for arrays.

### PR DESCRIPTION
**Pull request by mcabbott**
Closes #413, and #51, and half of #98. 

Questions:

* Should `jacobian(f, ps::Params)` return something other than an `IdDict()`?

* Should `matrix=true` be the default? Needs to be added to Params method.

Needs tests obviously.

### CODE REVIEW

**Comment by Roger-luo** [comment]
XRef: I implemented one in #188 as well but I didn't do anything on Params

**Comment by mcabbott** [comment]
Oh I completely missed that, sorry. Perhaps something to handle Params should just be bolted onto that.

**Comment by theogf** [comment]
@mcabbott I am trying to use your solution until #235 is merged and has a `Params` option, but I am confused by what you refer to when using `Zygote.forward`, is it `Zygote.forwarddiff`?

**Comment by mcabbott** [comment]
Ah no, sorry, it's now called `Zygote.pullback`. The name changed in v0.4 I think.

**Comment by theogf** [comment]
Thanks! It's working perfectly now!

**Pull request closed without merging**
