### PR TITLE
Fix #627

### LINKED ISSUE #627: Zygote errors on loading in Julia 1.0
The latest Zygote gives an error upon loading on Julia 1.0.
```julia
ERROR: LoadError: LoadError: UndefVarError: broadcasted not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at .\boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at .\loading.jl:1044
 [5] include at .\sysimg.jl:29 [inlined]
 [6] include(::String) at C:\Users\user\.julia\dev\Zygote\src\Zygote.jl:1
 [7] top-level scope at none:0
 [8] include at .\boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at .\loading.jl:1044
 [10] include(::Module, ::String) at .\sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at .\boot.jl:319 [inlined]
 [13] eval(::Expr) at .\client.jl:393
 [14] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\dev\Zygote\src\compiler\interface.jl:82
in expression starting at C:\Users\user\.julia\dev\Zygote\src\Zygote.jl:20
ERROR: Failed to precompile Zygote [e88e6eb3-aa80-5325-afca-941959d7151f] to C:\Users\user\.julia\compiled\v1.0\Zygote\4kbLI.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1203
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853
```
This is true for master as well.

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR fixes Zygote loading on Julia 1.0.

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
We would need this for sure

bors r+

**Comment by mohamed82008** [comment]
Let's please get a new release after this is merged.

**Comment by cossio** [comment]
Can we add a test for this? The definition before this PR:

```julia
Base.broadcasted(f, ps::Params) = broadcasted(f, ps.order)
```

was passing all tests, but it should be detected.

**Comment by mohamed82008** [comment]
I am assuming tests don't run on Julia 1.0 here.

**Comment by dhairyagandhi96** [comment]
Is that something Julia 1.3+?

**Comment by cossio** [comment]
Travis is running tests on Julia 1.3, I think.

**Comment by mohamed82008** [comment]
I think it's just that `broadcast` wasn't exported from `Base.Broadcast` in Julia 1.0. All you have to do to get the error in the issue is call `using Zygote` on Julia 1.0 :)

**Comment by cossio** [comment]
Hmmm, I have `Zygote 0.4.18` and I do `using Zygote` without error.

**Comment by cossio** [comment]
Also, `broadcasted` is not exported still in Julia 1.4.

**Comment by mohamed82008** [comment]
>Hmmm, I have Zygote 0.4.18 and I do using Zygote without error.

On Julia 1.0?

>Also, broadcasted is not exported still in Julia 1.4.

I think it is exported from `Base.Broadcast` to `Base` but not from `Base`.
```julia
julia> Base.broadcasted
broadcasted (generic function with 53 methods)
```

**Comment by cossio** [comment]
Oh you are right. I am running Julia 1.4.

**Comment by dhairyagandhi96** [comment]
I'd quite like registering on a green tick mark, if that's alright; just waiting on CI now.

**Pull request merged**
