### PR TITLE
Tag for SpecialFunctions@2

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
Ref #1137

### CODE REVIEW

**Comment by devmotion** [comment]
The test error (https://github.com/FluxML/Zygote.jl/runs/4554123422?check_suite_focus=true#step:6:178) is caused by CUDA, it appears in multiple other packages as well (e.g. DiffRules and ChainRules). The problem is that an ancient version of CUDA is pulled in since the newer releases are not compatible with SpecialFunctions 2 (this does not affect the installation of Zygote since it is only installed and loaded in the tests). The upcoming release of CUDA will support SpecialFunctions 2 which should resolve this problem.

**Comment by DhairyaLGandhi** [comment]
Right, I'm assuming CUDA is ready to be tagged? I saw that the version was bumped on master but hasn't been registered yet. We can register zygote with passing CI since it seems only registration of CUDA is the remaining piece for SpecialFunctions@2 which shouldn't hold us up too much.

**Comment by devmotion** [comment]
CUDA 3.6.0 is available now, can you rerun the tests? Hopefully they should pass 🙂

**Comment by devmotion** [comment]
Tests pass (apart from buildkite which wasn't resrarted) 🎉

**Comment by devmotion** [comment]
Good to go? Buildkite passed as well now :slightly_smiling_face:

**Comment by DhairyaLGandhi** [comment]
Yes, I'd wanted to get ci passing, thanks for bumping!

**Comment by devmotion** [comment]
Thanks, can you (or may I) register the new release? Or do you want to wait until tests pass on the master branch as well?

**Pull request merged**
